<div class="page-footer">
  <div class="row">
    <div class="col-sm-6 copyright">
      <div>&copy; 2016 Emanuel Lutheran Church</div>
      <div>Sunday services 9 and 10:45</div>
    </div>
    <div class="col-sm-6 contact">
      <div class="address">150 N. Palm Street La Habra, CA 90631</div>
      <div class="email"><a href="tel:+15626910656">(562) 691-0656</a> &ndash; <a href="mailto:churchinfo@elclh.org">churchinfo@elclh.org</a></div>
      <div class="facebook"><img src="/images/facebook.png" alt="Facebook" /> / <a href="https://www.facebook.com/emanuel.lutheran.1">emanuel.lutheran.1</a></div>
    </div>
  </div>
</div>
