<h2>This Week&rsquo;s Readings</h2>
<div class="module-content right">
    <div class="bible-readings">
        <div class="bible-readings-title">
            <strong>Sunday, October 12, 2025</strong>
            <br />
            <strong>Eighteenth Sunday after Pentecost</strong>
        </div>
        <ul class="bible-readings-list">
            <li>
                First Reading <span class="mobile-hide">(Old Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=2%20Kings%205%3A1-3%2C2%20Kings%205%3A7-15&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    2 Kings 5:1-3, 7-15c
                </a>
            </li>
            <li>
                Psalm:
                <a href="https://www.biblegateway.com/passage/?search=Psalm%20111&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Psalm 111
                </a>
            </li>
            <li>
                Second Reading <span class="mobile-hide">(New Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=2%20Timothy%202%3A8-15&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    2 Timothy 2:8-15
                </a>
            </li>
            <li>
                Gospel:
                <a href="https://www.biblegateway.com/passage/?search=Luke%2017%3A11-19&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Luke 17:11-19
                </a>
            </li>
        </ul>
    </div>

    <div class="elca-logo">
        <img src="images/home/elca-transparent.gif" alt="Evangelical Lutheran Church in America" class="elca-logo" />
    </div>
</div>