<h2>Welcome to Emanuel!</h2>
<div class="module-content left">
    <p>
        We invite you to join us on Sundays for traditional or contemporary
        worship.
    </p>
    <p>
        For first-time visitors make sure to check out the
        <a href="./who-we-are">Who We Are</a> and
        <a href="./worship">Worship</a> sections of our website.
    </p>
    <?php /* BEGIN: TEMP - Coronavirus Social Distancing Notice for X-Small, Small and Medium Viewports */ ?>
    <div class="hidden-lg">
      <p class="notice" style="font-weight: bold">
        Emanuel is allowing events on camps again. Small groups are able to meet
        with safety measured in place, and large groups also also slowly resuming
        meeting both inside and outdoors.  We are working to follow local, state
        and national guideline regarding safety.
      </p>
      <p>
        Check back here Sunday Morning for our
        <a href="#photo-carousel-container">Video Worship Service</a>.
      </p>
    </div>
    <?php /* END: TEMP - Coronavirus Social Distancing Notice for X-Small, Small and Medium Viewports */ ?>
</div>
<h2 class="worship-schedule-title">Worship Schedule</h2>
<div class="module-content left">
    <p class="notice">
      All Sunday worship services are at 10 am in the sanctuary (with safety protocols).
      Communion is served every Sunday.
    </p>
    <?php /*
    <p class="notice">All Sunday worship services offer communion</p>
    <ul class="list">
      <li class="service-time-entry clearfix">
        <div class="service-time">9:00 am</div>
        <div class="service-desc">Traditional Worship Service</div>
      </li>
      <li class="service-time-entry clearfix">
        <div class="service-time">10:00 am</div>
        <div class="service-desc">
          Education Hour &ndash; ages 3 through teens
        </div>
      </li>
      <li class="service-time-entry clearfix">
        <div class="service-time">10:45 am</div>
        <div class="service-desc">Praise Service</div>
      </li>
    </ul>
    */
    ?>
</div>
