<h2>This Week&rsquo;s Readings</h2>
<div class="module-content right">
    <div class="bible-readings">
        <div class="bible-readings-title">
            <strong>Sunday, September 1, 2024</strong>
            <br />
            <strong>Fifteenth Sunday after Pentecost</strong>
        </div>
        <ul class="bible-readings-list">
            <li>
                First Reading <span class="mobile-hide">(Old Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=Deuteronomy%204%3A1-2%2CDeuteronomy%204%3A6-9&version=NRSVUE" target="_blank">
                    Deuteronomy 4:1-2, 6-9
                </a>
            </li>
            <li>
                Psalm:
                <a href="https://www.biblegateway.com/passage/?search=Psalm%2015&version=NRSVUE" target="_blank">
                    Psalm 15
                </a>
            </li>
            <li>
                Second Reading <span class="mobile-hide">(New Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=James%201%3A17-27&version=NRSVUE" target="_blank">
                    James 1:17-27
                </a>
            </li>
            <li>
                Gospel:
                <a href="https://www.biblegateway.com/passage/?search=Mark%207%3A1-8%2C14-15%2C21-23&version=NRSVUE" target="_blank">
                    Mark 7:1-8, 14-15, 21-23
                </a>
            </li>
        </ul>
    </div>

    <div class="elca-logo">
        <img src="images/home/elca-transparent.gif" alt="Evangelical Lutheran Church in America" class="elca-logo" />
    </div>
</div>