<h2>This Week&rsquo;s Readings</h2>
<div class="module-content right">
    <div class="bible-readings">
        <div class="bible-readings-title">
            <strong>Sunday, November 23, 2025</strong>
            <br />
            <strong>Christ the King Sunday</strong>
        </div>
        <ul class="bible-readings-list">
            <li>
                First Reading <span class="mobile-hide">(Old Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=Jeremiah%2023%3A1-6&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Jeremiah 23:1-6
                </a>
            </li>
            <li>
                Psalm:
                <a href="https://www.biblegateway.com/passage/?search=Psalm%2046&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Psalm 46
                </a>
            </li>
            <li>
                Second Reading <span class="mobile-hide">(New Testament)</span>:
                <a href="https://www.biblegateway.com/passage/?search=Colossians%201%3A11-20&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Colossians 1:11-20
                </a>
            </li>
            <li>
                Gospel:
                <a href="https://www.biblegateway.com/passage/?search=Luke%2023%3A33-43&version=NRSVUE" target="_blank" rel="noopener noreferrer nofollow">
                    Luke 23:33-43
                </a>
            </li>
        </ul>
    </div>

    <div class="elca-logo">
        <img src="images/home/elca-transparent.gif" alt="Evangelical Lutheran Church in America" class="elca-logo" />
    </div>
</div>