<div id="homePageCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#homePageCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#homePageCarousel" data-slide-to="1"></li>
    <li data-target="#homePageCarousel" data-slide-to="2"></li>
    <li data-target="#homePageCarousel" data-slide-to="3"></li>
    <li data-target="#homePageCarousel" data-slide-to="4"></li>
    <li data-target="#homePageCarousel" data-slide-to="5"></li>
    <li data-target="#homePageCarousel" data-slide-to="6"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="./images/home/blanket-making.jpg" alt="Blanket Making for Community Center" />
      <div class="carousel-caption">
        <p>Blanket Making for Community Center</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/easter-sunday.jpg" alt="Easter Sunday" />
      <div class="carousel-caption">
        <p>Easter Sunday</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/free-for-all.jpg" alt="Free-For-All" />
      <div class="carousel-caption">
        <p>Free-For-All</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/sunday-school.jpg" alt="Science Lesson about God&rsquo;s Wonder" />
      <div class="carousel-caption">
        <p>Science Lesson about God&rsquo;s Wonder</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/sisters-in-christ.jpg" alt="Sisters in Christ" />
      <div class="carousel-caption">
        <p>Sisters in Christ</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/womens-retreat.jpg" alt="Women&rsquo;s retreat" />
      <div class="carousel-caption">
        <p>Women&rsquo;s retreat</p>
      </div>
    </div>
    <div class="item">
      <img src="" data-img-src="./images/home/preschool-program.jpg" alt="Preschool Program" />
      <div class="carousel-caption">
        <p>Preschool Program</p>
      </div>
    </div>
  </div>
</div> <!-- /.carsousel -->
