<h2>Upcoming Events</h2>
<div class="upcoming-events-content">
  <p class="notice" style="font-weight: bold">
    Emanuel will not have any groups gathering for worship, Bible Study, small
    groups or meetings effective today through at least April 5.
  </p>
  <p>
    Please <a href="./coronavirus-precautions">click here</a> for the list of
    online ways we are continuing our ministry during this time and for a letter
    from Pastor Cate Luehr.
  </p>
  <p>Check back here Sunday Morning for our Video Worship Service</p>
</div>
