<?php
  require_once('./app-code/helper-functions.php');
?>
<h2>Worship Audio</h2>
<div class="module-content right">
  <p>
    Did you miss worshiping with us?  Here&rsquo;s an audio recording of a
    recent worship service; you can listen online!  And listen to recordings of
    previous services in our <a href="./worship-audio">audio library</a>.
  </p>
  <?php
    $audioFilesJson = file_get_contents('./app-data/audio-files.json');
    $audioFiles = json_decode($audioFilesJson, TRUE);
    date_sort_descending($audioFiles);
    $audioFile = $audioFiles[0];
    $fileDateTime = strtotime($audioFile['dateTime']);
    $date = date('l, F j, Y', $fileDateTime);
    $time = date('g:i A', $fileDateTime);
    $safePrefix = get($audioFile['prefix']);
    $safeSpeaker = get($audioFile['speaker']);
    $path = $audioFile['path'];
  ?>
  <div class="audio-file-entry">
    <div class="icon">
      <img src="images/audio.png" alt="Audio" />
    </div>
    <div class="description">
      <p>
        <?= $safePrefix === NULL ? NULL : $safePrefix . '<br />' ?>
        <?= $date ?>
        <br  />
        <?= $time ?>
        <?= $safeSpeaker === NULL ? NULL : '<br /><br />' . $safeSpeaker ?>
      </p>
    </div>
    <div class="player">
      <audio controls preload="none">
        <source src="<?= $path ?>" type="audio/mp4" />
        <p>Your browser does not support HTML5 audio.</p>
      </audio>
    </div>
    <div class="download">
      <a href="<?= $path ?>">
        <strong>Download (M4A)</strong>
      </a>
    </div>
  </div>
  <div class="elca-logo">
    <img src="images/home/elca-transparent.gif" alt="Evangelical Lutheran Church in America" class="elca-logo" />
  </div>
</div>
