<h2>Welcome to Emanuel!</h2>
<div class="module-content left">
    <p>
        We invite you to join us on Sundays for traditional or contemporary
        worship.
    </p>
    <p>
        For first-time visitors make sure to check out the
        <a href="./who-we-are">Who We Are</a> and
        <a href="./worship">Worship</a> sections of our website.
    </p>
</div>
<h2 class="worship-schedule-title">Worship Schedule</h2>
<div class="module-content left">
    <p class="notice">All Sunday worship services offer communion.</p>
    <?php /* <ul class="list">
      <li class="service-time-entry clearfix">
        <div class="service-time">9:00 am</div>
        <div class="service-desc">Traditional Worship Service</div>
      </li>
      <li class="service-time-entry clearfix">
        <div class="service-time">10:00 am</div>
        <div class="service-desc">
          Education Hour &ndash; ages 3 through 6<sup>th</sup> grade
        </div>
      </li>
      <li class="service-time-entry clearfix">
        <div class="service-time">10:45 am</div>
        <div class="service-desc">Praise Service</div>
      </li>
    </ul> */?>
    <p class="notice">
      For December 5, 2021 through January 2, 2022, we will have only one
      worship service on Sunday mornings at 10:00 am.
    </p>
    <p>
      Emanuel worship services are also on
      <a href="https://www.facebook.com/emanuel.lutheran.1" target="_blank">Facebook</a>
      and
      <a href="https://www.youtube.com/channel/UC4Fu6qvPdYF2MM92JzoU9uA" target="_blank">YouTube</a>.
    </p>
    <p>
      <strong>If you need closed-captioning,</strong> view our worship services
      on YouTube via
      <a href="https://www.youtube.com/channel/UC4Fu6qvPdYF2MM92JzoU9uA" target="_blank">this link</a>.
      Be sure to click the <strong>CC</strong> icon for auto-generated captioning.
    </p>
</div>
