<h2 class="left-bottom">Location &amp; Contact</h2>
<div class="module-content left">
  <p class="address">
    Emanuel Lutheran Church<br />
    150 N. Palm Street<br />
    La Habra, CA 90631<br />
    <a href="tel:+15626910656">(562) 691-0656</a>
  </p>
  <p>
    <a href="http://local.google.com/local?f=q&hl=en&q=150%20N.%20Palm%20Street,%20La%20Habra,%20CA%2090631" target="_blank">Map &amp; Directions</a>
  </p>
  <div class="map-container">
    <img src="images/home/map.gif" alt="Map to Emanuel Lutheran Church, La Habra, CA" />
  </div>

</div>
