<div class="page-header">
  <div class="row">
    <div class="col-xs-12 col-sm-7">
      <div class="main-title-wrap">
        <?php if (basename($_SERVER['PHP_SELF']) == 'index.php'): ?>
          <h1 class="main-title">Emanuel Lutheran Church</h1>
        <?php else: ?>
          <div class="main-title">Emanuel Lutheran Church</div>
        <?php endif; ?>
      </div>
      <div class="sub-title">&ldquo;God with Us&rdquo;</div>
      <div class="header-svc-time">Sunday services 9 and 10:45</div>
    </div>
    <div class="col-xs-12 col-sm-5">
      <div class="header-verse-container">
        <div class="header-verse">
          &ldquo;For by grace you have been saved, through faith. And this is not of your own doing; it is the gift of God.&rdquo;
        </div>
        <div class="header-verse-ref">Ephesians 2:8</div>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-default">
  <div class="container layout-v2">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="mobile-menu-toggle">Menu</span>
      </button>
      <a class="navbar-brand" href="./">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About Us <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./who-we-are">Who We Are</a></li>
            <li><a href="./staff">Staff</a></li>
            <li><a href="http://www.elca.org" target="_blank">ELCA</a></li>
            <li><a href="http://www.pacificasynod.org" target="_blank">Pacific Synod</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Worship <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./worship">Services</a></li>
            <li><a href="./worship-audio">Audio</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ministries <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./music">Music</a></li>
            <li><a href="./youth">Youth and Children</a></li>
            <li><a href="./bible-studies">Bible Studies</a></li>
            <?php /*<li><a href="./seniors">Seniors</a></li>*/ ?>
            <li><a href="./stephen-ministry">Stephen Ministry</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Outreach <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./outreach">Hearts and Hands Outreach</a></li>
            <li><a href="./community">Community Groups</a></li>
            <li><a href="./study-buddies">Study Buddies</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Preschool <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./preschool">Preschool</a></li>
            <li><a href="./preschool-staff">Staff</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Giving <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./giving">Online Giving</a></li>
          </ul>
        </li>
        <li class="dropdown news-and-events">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">News &amp; Events <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="./calendar">Calendar</a></li>
            <li><a href="./newsletter">Newsletter</a></li>
          </ul>
        </li>
      </ul>
    </div> <!--/.nav-collapse -->
  </div>
</nav>
